In [20]:
import warnings
warnings. simplefilter(action='ignore', category=Warning)
import pandas as pd
import numpy as np
from tabulate import tabulate

In [2]:
def GoldenCrossverSignal(name):
    path = f'../Data/{name}.csv'
    data = pd.read_csv(path, parse_dates=['Datetime'], index_col='Datetime')
    data['Prev_Close'] = data.Close.shift(1)
    data['20_SMA'] = data.Prev_Close.rolling(window=20, min_periods=20).mean()
    data['50_SMA'] = data.Prev_Close.rolling(window=50, min_periods=50).mean()
    data['Signal'] = 0
    data['Signal'] = np.where(data['20_SMA'] > data['50_SMA'], 1, 0)
    data['Position'] = data.Signal.diff()
    df_pos = data[(data['Position'] == 1) | (data['Position'] == -1)].copy()
    df_pos['Position'] = df_pos['Position'].apply(lambda x: 'Buy' if x == 1 else 'Sell')
    return df_pos

In [3]:
data = GoldenCrossverSignal('HDFCBANK')

In [4]:
required_df = data[(data.index >= data[data['Position'] == 'Buy'].index[0]) & (data.index <= data[data['Position'] == 'Sell'].index[-1])]

In [5]:
required_df

,Open,High,Low,Close,Adj Close,Volume,Prev_Close,20_SMA,50_SMA,Signal,Position
Datetime,,,,,,,,,,,
2023-06-02 12:05:00+05:30,1609.949951,1610.199951,1608.550049,1609.949951,1609.949951,43058,1610.150024,1607.632507,1607.595005,1,Buy
2023-06-02 14:50:00+05:30,1605.250000,1605.349976,1603.500000,1603.500000,1603.500000,70338,1605.400024,1608.097498,1608.241001,0,Sell
2023-06-05 10:00:00+05:30,1613.500000,1614.900024,1613.349976,1614.599976,1614.599976,105226,1613.400024,1608.967499,1608.816997,1,Buy
2023-06-05 12:55:00+05:30,1607.750000,1608.000000,1607.699951,1607.949951,1607.949951,59085,1607.750000,1611.349988,1611.579993,0,Sell
2023-06-06 15:20:00+05:30,1602.349976,1602.949951,1601.250000,1602.599976,1602.599976,202719,1602.349976,1596.540002,1596.525996,1,Buy
2023-06-07 12:10:00+05:30,1596.750000,1599.699951,1596.750000,1598.349976,1598.349976,365748,1596.849976,1600.439990,1600.622993,0,Sell
2023-06-07 14:05:00+05:30,1603.250000,1603.250000,1601.699951,1602.400024,1602.400024,264873,1603.250000,1601.139996,1600.997993,1,Buy
2023-06-08 13:15:00+05:30,1615.300049,1616.800049,1614.949951,1616.400024,1616.400024,106780,1615.349976,1618.397504,1618.669001,0,Sell
2023-06-09 11:45:00+05:30,1615.500000,1616.699951,1615.449951,1616.050049,1616.050049,84569,1615.500000,1613.530005,1613.472002,1,Buy
2023-06-09 15:00:00+05:30,1612.800049,1613.599976,1611.550049,1611.550049,1611.550049,108782,1612.750000,1614.857495,1614.918999,0,Sell
2023-06-13 10:05:00+05:30,1604.900024,1607.099976,1603.800049,1604.349976,1604.349976,216671,1604.900024,1603.050000,1603.023992,1,Buy
2023-06-13 13:05:00+05:30,1603.150024,1603.550049,1602.050049,1602.849976,1602.849976,62749,1603.199951,1603.942499,1604.110000,0,Sell
2023-06-14 09:50:00+05:30,1603.349976,1604.449951,1602.150024,1603.599976,1603.599976,153224,1603.400024,1602.910004,1602.802998,1,Buy
2023-06-14 14:30:00+05:30,1605.449951,1607.400024,1605.250000,1605.750000,1605.750000,83291,1605.400024,1608.397498,1608.469995,0,Sell
2023-06-16 10:15:00+05:30,1594.800049,1595.849976,1594.050049,1595.050049,1595.050049,67499,1594.500000,1587.157501,1587.110999,1,Buy
2023-06-16 14:10:00+05:30,1597.750000,1598.949951,1596.900024,1598.400024,1598.400024,94247,1597.300049,1597.179999,1597.200000,0,Sell
2023-06-16 14:15:00+05:30,1599.000000,1599.349976,1598.000000,1598.349976,1598.349976,132598,1598.400024,1597.332501,1597.329001,1,Buy
2023-06-19 13:35:00+05:30,1601.900024,1604.500000,1601.550049,1602.650024,1602.650024,153543,1601.900024,1607.732501,1607.942004,0,Sell
2023-06-20 12:45:00+05:30,1597.750000,1598.099976,1596.900024,1597.500000,1597.500000,75168,1597.750000,1596.329999,1596.235999,1,Buy
2023-06-23 09:15:00+05:30,1638.800049,1640.349976,1635.550049,1638.150024,1638.150024,0,1644.800049,1646.789996,1647.257000,0,Sell
2023-06-23 10:55:00+05:30,1654.449951,1655.500000,1654.000000,1654.000000,1654.000000,69430,1654.949951,1648.357495,1648.181997,1,Buy
2023-06-23 13:50:00+05:30,1647.699951,1648.849976,1646.849976,1647.250000,1647.250000,82343,1647.849976,1653.879980,1654.016990,0,Sell
2023-06-26 12:30:00+05:30,1641.750000,1642.250000,1640.500000,1641.000000,1641.000000,49575,1641.949951,1641.270001,1641.225002,1,Buy
2023-06-26 13:15:00+05:30,1636.750000,1637.250000,1636.199951,1637.199951,1637.199951,74915,1636.900024,1640.070007,1640.091003,0,Sell

In [13]:
# Name, Entry TIme, Entry PRice, QTY, Exit Time, Exit Price
class Backtest:
    def __init__(self):
        self.columns = ['Equity Name', 'Trade', 'Entry Time', 'Entry Price', 'Exit Time', 'Exit Price', 'Quantity', 'Position Size', 'PNL', '% PNL']
        self.backtesting = pd.DataFrame(columns=self.columns)

    def buy(self, equity_name, entry_time, entry_price, qty):
        self.trade_log = dict(zip(self.columns, [None] * len(self.columns)))
        self.trade_log['Trade'] = 'Long Open'
        self.trade_log['Quantity'] = qty
        self.trade_log['Position Size'] = round(self.trade_log['Quantity'] * entry_price, 3)
        self.trade_log['Equity Name'] = equity_name
        self.trade_log['Entry Time'] = entry_time
        self.trade_log['Entry Price'] = round(entry_price, 2)

    def sell(self, exit_time, exit_price, exit_type, charge):
        self.trade_log['Trade'] = 'Long Closed'
        self.trade_log['Exit Time'] = exit_time
        self.trade_log['Exit Price'] = round(exit_price, 2)
        self.trade_log['Exit Type'] = exit_type
        self.trade_log['PNL'] = round((self.trade_log['Exit Price'] - self.trade_log['Entry Price']) * self.trade_log['Quantity'] - charge, 3)
        self.trade_log['% PNL'] = round((self.trade_log['PNL'] / self.trade_log['Position Size']) * 100, 3)
        self.trade_log['Holding Period'] = exit_time - self.trade_log['Entry Time']
        self.backtesting = pd.concat([self.backtesting, pd.DataFrame([self.trade_log])], ignore_index=True)
    def stats(self):
        df = self.backtesting
        parameters = ['Total Trade Scripts', 'Total Trade', 'PNL',  'Winners', 'Losers', 'Win Ratio','Total Profit', 'Total Loss', 'Average Loss per Trade', 'Average Profit per Trade', 'Average PNL Per Trade', 'Risk Reward']
        total_traded_scripts = len(df['Equity Name'].unique())
        total_trade = len(df.index)
        pnl = df.PNL.sum()
        winners = len(df[df.PNL > 0])
        loosers = len(df[df.PNL <= 0])
        win_ratio = str(round((winners/total_trade) * 100, 2)) + '%'
        total_profit = round(df[df.PNL > 0].PNL.sum(), 2)
        total_loss  = round(df[df.PNL <= 0].PNL.sum(), 2)
        average_loss_per_trade = round(total_loss/loosers, 2)
        average_profit_per_trade = round(total_profit/winners, 2)
        average_pnl_per_trade = round(pnl/total_trade, 2)
        risk_reward = f'1:{-1 * round(average_profit_per_trade/average_loss_per_trade, 2)}'
        data_points = [total_traded_scripts,total_trade,pnl,winners, loosers, win_ratio, total_profit, total_loss, average_loss_per_trade, average_profit_per_trade, average_pnl_per_trade, risk_reward]
        data = list(zip(parameters,data_points ))
        print(tabulate(data, ['Parameters', 'Values'], tablefmt='psql'))

In [16]:
bt = Backtest()
capital = 50000
#scripts = ['RELIANCE', "TCS", 'INFY', 'SBIN', 'HDFCBANK']
nifty_100 = pd.read_csv('ind_nifty100list.csv')
for stock in nifty_100.Symbol:
    data = GoldenCrossverSignal(stock)
    required_df = data[(data.index >= data[data['Position'] == 'Buy'].index[0]) & (data.index <= data[data['Position'] == 'Sell'].index[-1])]
    for index, data in required_df.iterrows():
        if(data.Position == 'Buy'):
            qty = capital // data.Open
            bt.buy(stock, index, data.Open, qty)
        else:
            bt.sell(index, data.Open, 'Exit Trigger', 0)

In [17]:
bt.backtesting

,Equity Name,Trade,Entry Time,Entry Price,Exit Time,Exit Price,Quantity,Position Size,PNL,% PNL,Exit Type,Holding Period
0,ABB,Long Closed,2023-06-02 10:10:00+05:30,3970.15,2023-06-02 13:35:00+05:30,3985.70,12.0,47641.799,186.6,0.392,Exit Trigger,0 days 03:25:00
1,ABB,Long Closed,2023-06-02 15:15:00+05:30,4019.15,2023-06-05 11:25:00+05:30,4007.45,12.0,48229.799,-140.4,-0.291,Exit Trigger,2 days 20:10:00
2,ABB,Long Closed,2023-06-05 15:05:00+05:30,4020.00,2023-06-06 12:35:00+05:30,4052.60,12.0,48240.000,391.2,0.811,Exit Trigger,0 days 21:30:00
3,ABB,Long Closed,2023-06-06 14:35:00+05:30,4072.10,2023-06-08 10:20:00+05:30,4106.45,12.0,48865.201,412.2,0.844,Exit Trigger,1 days 19:45:00
4,ABB,Long Closed,2023-06-08 14:55:00+05:30,4110.05,2023-06-09 12:00:00+05:30,4118.65,12.0,49320.598,103.2,0.209,Exit Trigger,0 days 21:05:00
...,...,...,...,...,...,...,...,...,...,...,...,...
1613,ZOMATO,Long Closed,2023-06-20 15:15:00+05:30,75.85,2023-06-21 12:10:00+05:30,75.45,659.0,49985.149,-263.6,-0.527,Exit Trigger,0 days 20:55:00
1614,ZOMATO,Long Closed,2023-06-23 11:25:00+05:30,74.75,2023-06-23 14:10:00+05:30,74.40,668.0,49933.000,-233.8,-0.468,Exit Trigger,0 days 02:45:00
1615,ZOMATO,Long Closed,2023-06-26 09:35:00+05:30,74.85,2023-06-26 10:05:00+05:30,74.40,668.0,49999.799,-300.6,-0.601,Exit Trigger,0 days 00:30:00
1616,ZOMATO,Long Closed,2023-06-26 10:45:00+05:30,74.65,2023-06-26 14:35:00+05:30,74.85,669.0,49940.851,133.8,0.268,Exit Trigger,0 days 03:50:00
1617,ZOMATO,Long Closed,2023-06-27 09:30:00+05:30,75.05,2023-06-27 14:50:00+05:30,75.95,666.0,49983.302,599.4,1.199,Exit Trigger,0 days 05:20:00

In [18]:
bt.backtesting.to_csv('Backtest.csv')

In [21]:
bt.stats()

+--------------------------+------------+
| Parameters               | Values     |
|--------------------------+------------|
| Total Trade Scripts      | 100        |
| Total Trade              | 1618       |
| PNL                      | 48603.92   |
| Winners                  | 629        |
| Losers                   | 989        |
| Win Ratio                | 38.88%     |
| Total Profit             | 274392.11  |
| Total Loss               | -225788.19 |
| Average Loss per Trade   | -228.3     |
| Average Profit per Trade | 436.24     |
| Average PNL Per Trade    | 30.04      |
| Risk Reward              | 1:1.91     |
+--------------------------+------------+